#------------------------------------------------------------------------------
# This is only a proof of concept
#------------------------------------------------------------------------------

#------------------------------------------------------------------------------
# Variables
#------------------------------------------------------------------------------
@Sonos_WebApi_HostAddress = http://localhost:32788


#------------------------------------------------------------------------------
# Get wav file
#------------------------------------------------------------------------------
GET {{Sonos_WebApi_HostAddress}}/api/image/GetItem/test.wav
Accept: application/json

###

#------------------------------------------------------------------------------
# Get mp3 file
#------------------------------------------------------------------------------
GET {{Sonos_WebApi_HostAddress}}/api/image/GetItem/test.mp3
Accept: application/json

###

#------------------------------------------------------------------------------
# Play wav file on Sonos
#------------------------------------------------------------------------------
POST {{Sonos_WebApi_HostAddress}}/api/sonos/ProcessWav

###

#------------------------------------------------------------------------------
# Play mp3 file on Sonos
#------------------------------------------------------------------------------
POST {{Sonos_WebApi_HostAddress}}/api/sonos/ProcessMp3